### ISSUE TITLE
[REFACTOR] ChatView QA 반영

### ISSUE THREAD

**Issue by choijungp** [APP-iOS4/ANBD#104]
## Description
마루의 QA 반영

## Todo
- [x] 다크모드시에도 글씨보이게 (gray900)
- [x] ChatListCell에서 상대방과 마지막 메시지 사이 간격 줄이기
- [x] ChatDetailView에서 쩜쩜쩜 버튼 font 키우기
