### ISSUE TITLE
[REFACTOR] Model 04/14멘토링 반영

### ISSUE THREAD

**Issue by jihoooo97** [APP-iOS4/ANBD#119]
## Description
04/14 멘토링 반영

## Before
멘토링 받기 전 지적?받은 부분이 있음

## After
멘토링 반영해서 수정

## Todo

- [ ] 명시적인 네이밍 고려해보기
- [x] extension 분리한 것 다시 합치기
- [x]  의미없는 추상화 공통부분 고려해보기
- [x] Query 잘못들어간 부분 수정
- [x] 페이지네이션 갯수 유동적으로 바꿀 수 있게 수정
