### ISSUE TITLE
[FEATURE] 디자인 변경 및 기능추가

### ISSUE THREAD

**Issue by Upcircle2** [APP-iOS4/ANBD#129]
## Description
디자인 변경 및 기능 추가

## Todo

- [ ]  ListView 스타일 변경 - 구성요소의 Text 시작점 통일
- [x]  현재 user,article,trade 검색기능은 Title 검색만 가능함. UUID 로도 검색 가능하게 수정
- [ ]  userList-유저가 작성한 댓글 Detailview에 표시
- [ ]  articleList-게시물에 달린 댓글 Detailview에 표시
- [ ] userListDetailView 해당 유저 userLevel 변경 기능 추가
- [x] consumer, admin 유저목록 2분할
- [x] inquiry 추후 연결할 임시미 뷰 생성
- [x] 배너 열람, 첨삭기능 추가
