### ISSUE TITLE
[FEATURE] Trade Model

### ISSUE THREAD

**Issue by jihoooo97** [APP-iOS4/ANBD#14]
## Description
Trade 모델 및 전반적인 Firestore 작업

## Todo
- [x] Trade 모델 작업
- [ ] Trade Repository 작업
- [ ] Trade Usecase 작업 
- [ ] 전반적인 문서화 작업
