### ISSUE TITLE
[FEATURE] Article, Trade 썸네일 이미지 작업

### ISSUE THREAD

**Issue by jihoooo97** [APP-iOS4/ANBD#142]
## Description
리스트의 빠른 갱신을 위한 썸네일 이미지 작업

## Todo
- [x] Article, Trade에 썸네일 이미지 path 필드 추가
- [ ] 데이터로 가공해서 전달해줄지..? 는 고민
- [x] 이미지 업로드 시 메인 이미지, 썸네일 이미지 분리

## Etc
