### ISSUE TITLE
[FEATURE]Chat Model 

### ISSUE THREAD

**Issue by UnGwan** [APP-iOS4/ANBD#16]
## Description
Chat 모델 및 전반적인 Firestore 작업

## Todo
- [x] Chat 모델 작업
- [x] Chat Repository 작업
- [x] Chat Usecase 작업 
- [x] 전반적인 문서화 작업
- [ ]  실시간 채팅 작업 
- [ ]  채팅 데이터 페이징 작업
