### ISSUE TITLE
[FEATURE] 마이페이지 유저 정보 수정 및 유저 ANBD 리스트

### ISSUE THREAD

**Issue by marukim365** [APP-iOS4/ANBD#175]
## Description
- 마이페이지 QA 반영
- 타 유저 정보 확인하기 작업

## Todo
- [x] 유저 정보에서 이메일과 선호지역 그룹화 작업
- [x] 리스트가 비어있을 때 나타낼 공통 뷰 구현
- [x] 다른 유저 정보를 확인하기 위해 분기를 구별하는 작업 중

## Etc
아직 다른 유저 정보 확인하기 기능을 끝내지 못함
UserDefaults 수정이 필요해서 수정할 예정 -> User를 모두 저장하는 것이 아니라, 필요한 데이터만 저장하기
