### ISSUE TITLE
[REFACTOR] Home, Chat 피드백 · QA 반영 

### ISSUE THREAD

**Issue by choijungp** [APP-iOS4/ANBD#176]
## Description
4월 3째주 유민영 강사님 피드백 및 QA 적용

## After
피드백 반영 ~

## Todo

- [x] 채팅방 신고하기 버튼 색상 변경
- [x] 채팅 Trade에 제목과 상품 설명 간격 조절
- [x] 홈, 서치, 채팅, 신고 페이지 navigationbar 이전 title 안보이게
- [x] 홈 ArticleCell 썸네일 및 리스트 다른 탭 다녀와야 뜨는 것 해결
