### ISSUE TITLE
[REFACTOR] trade 피드백 반영

### ISSUE THREAD

**Issue by juri123123** [APP-iOS4/ANBD#177]
## Description
trade 피드백 및 QA 반영

## Todo
- [x] trade 글 작성 후에 카테고리, 지역 초기화 하기
- [x] 찜 누를 때 사진 깜빡임 버그
- [x] 카테고리랑 본문 content font size 조절
- [ ] trade 등록 시 사진 등록 버튼
- [x] 카테고리/지역 시트 추가
