### ISSUE TITLE
[REFACTOR] Chat Model 전반적인 기능 수정 

### ISSUE THREAD

**Issue by UnGwan** [APP-iOS4/ANBD#178]
## Description
- 무한 트래픽 방지 리스너 수정 
- 채팅방 나가기 & 채팅방 읽음 유무 방식 수정 

## Todo
- [x] 채팅방 리스트 리스너 해제 작업
- [x] 채팅방 나가기 방식 수정
- [x] 상대방 메시지 읽음 유무 수정
