### ISSUE TITLE
[FEATURE] Chat - Model 연결 (2)

### ISSUE THREAD

**Issue by choijungp** [APP-iOS4/ANBD#187]
## Description
채팅 View 모델 연결 (2)

## Todo
- [x] 채팅방 나가기
- [x] Trade 연결 
- [x] 메시지 읽음 유무
- [x] 메시지 날짜 구분선 
- [ ] 상대방 프로필 띄우기 
- [ ]  ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️푸시알람 ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️ ❗️

## Etc
굉장히 ~~~ 기대가 됩니다 .... @UnGwan 운관님  ..... 잘부탁드려용
