### ISSUE TITLE
[FEATURE] 유저디폴트 수정 및 로그인 부가 기능 추가

### ISSUE THREAD

**Issue by marukim365** [APP-iOS4/ANBD#193]
## Description
- UserDefaults에 기존에는 유저의 모든 정보를 저장하고 있었지만, 유저의 아이디/이메일/닉네임/프로필 이미지 경로만 저장하는 것으로 변경
- 회원가입, 닉네임 변경 시 닉네임 20자 제한걸기
- 로그인 화면에서 에러 문구 위로 올리기
- 회원가입 시 사용자 선호 지역 적용 안되는 문제 수정
- 디바운스 값 확인해보기

## Todo
- [x] UserDefaults 수정
- [x] 회원 가입, 닉네임 변경 시 닉네임 20자 제한
- [x] 로그인 화면에서 에러 문구 위로 올리기
- [x] 회원가입 시 사용자 선호 지역 문제 해결
- [x] 디바운스 값 확인해보기

## Etc
N/A
