### ISSUE TITLE
[FEATURE] 로그인 실패 시 Alert 창 띄우기

### ISSUE THREAD

**Issue by marukim365** [APP-iOS4/ANBD#241]
## Description
- 로그인 실패 시  Alert 창 띄우기
- 유저의 기본 프로필 이미지 수정하기
- UserDefaults의 UserInfo 없애기

## Todo
- [x] 로그인 실패 시  Alert 창 띄우기
- [x] 유저의 기본 프로필 이미지 수정하기
- [ ] ~~UserDefaults의 UserInfo 없애기~~

## Etc
UserDefaults의 UserInfo 없애기 작업은 다음에 작업하도록 하겠습니다!
