### ISSUE TITLE
[FEATURE] Trade Usecase 작업

### ISSUE THREAD

**Issue by jihoooo97** [APP-iOS4/ANBD#25]
## Description
앱단의 ViewModel에서 활용할 TradeUsecase를 작업할 것입니다.

## Todo
- [ ] Trade 거래글 생성 기능 (사진, Trade 정보 upload)
- [ ] Trade 거래글 읽기 기능 (전체, [나,바]인 글, 거래 상태, 작성자 ID 별)
- [ ] Trade 거래글 수정 기능 (사진, Trade 정보 update, 나<->바 간 수정, 거래 상태 변경)
- [ ] Trade 거래글 삭제 기능

## Etc
