### ISSUE TITLE
[REFACTOR] QA 반영 및 유저의 좋아요, 찜 리스트 수정

### ISSUE THREAD

**Issue by marukim365** [APP-iOS4/ANBD#259]
## Description
- 강사님의 QA 반영
- 유저의 좋아요, 찜 리스트 업데이트 수정

## Before
- 회원가입 시, 약관 모두 동의 버튼 헷갈림
- 유저 프로필 수정 시, 수정 버튼의 레이블이 헷갈림
- 유저의 좋아요, 찜 리스트 내에서 취소 시, 리스트가 바로 반영되지 않음

## After
- 회원가입 시, 약관 모두 동의 버튼 변경
- 유저 프로필 수정 시, 수정 버튼의 레이블 변경
- 유저의 좋아요, 찜 리스트 내에서 취소 시, 리스트가 바로 반영되도록 변경

## Todo

- [x]  회원가입 시, 약관 모두 동의 버튼 변경
- [x]  유저 프로필 수정 시, 수정 버튼의 레이블 변경
- [x] 유저의 좋아요, 찜 리스트 내에서 취소 시, 리스트가 바로 반영되도록 변경
