### ISSUE TITLE
[REFACTOR] trade 피드백 반영

### ISSUE THREAD

**Issue by juri123123** [APP-iOS4/ANBD#260]
## Description
튜나샘 피드백 반영 

## Todo

- [x]  사진 중복 처리 버그 수정 
- [x]  디테일뷰 하단 상품 이름 길어지면 어떻게 할지 투표
- [x] 필터 캡슐 위아래 패딩 조절
