### ISSUE TITLE
[REFACTOR] Article-QA 반영

### ISSUE THREAD

**Issue by rlvy0513** [APP-iOS4/ANBD#277]
## Description
마루 QA 반영하기 !

## Todo
- [x] 탈퇴한 사용자 프로필 이미지 처리
- [x] 글쓰기에 텍스트 있으면 알럿 띄우기
- [x] 취소 누르면 키보드 내려가는거 추가
- [x] 게시글, 댓글 이름, 시간부분 통일
- [x] 댓글 메뉴버튼 터치감 개선
- [x] 수정사항 없으면 완료 버튼 안보이도록 수정
- [x] 탈퇴한 사용자 게시글 신고하기 다시 추가
- [x] 다크모드 대응

## Etc
N/A
