### ISSUE TITLE
[Feature && Fix] 채팅방 버그 수정 및 일부 기능 추가 

### ISSUE THREAD

**Issue by UnGwan** [APP-iOS4/ANBD#278]
## Description
QA기반 채팅방 버그들 수정  

## Todo
- [x] 채팅방 생성시 신고 가능하도록 
- [x] 신고하기에 이모지 추가 
- [x] 채팅방 상대가 회원탈퇴 시 예외 처리 적용 
- [x] 채팅 상대 닉네임 변경시 버그 발생
- [x] 전체적인 리팩토링
