### ISSUE TITLE
[REFACTOR] 마이페이지 QA 및 체크리스트 반영 작업

### ISSUE THREAD

**Issue by marukim365** [APP-iOS4/ANBD#279]
## Description
팀원 QA 및 체크리스트 반영 

## Before
- 로그아웃 Alert 확인 버튼 색상 HeartRed
- 유저 정보 수정 시, 수정 사항 있어도 취소 버튼 시 바로 취소
- 다크모드에서 피커 레이블을 읽을 수 없음
- 체크리스트에 맞게 앱 버전 정보, 개발자 정보, 문의 이메일 넣어주기

## After
- 로그아웃 Alert 확인 버튼 색상 Accent
- 유저 정보 수정 시, 수정 사항 있으면 Alert 띄어주기
- 다크모드에서 피커 색상 수정
- 체크리스트에 맞게 앱 버전 정보, 개발자 정보, 문의 이메일 넣어주기

## Todo

- [x]  로그아웃 Alert 확인 버튼 색상 Accent
- [x]  유저 정보 수정 시, 수정 사항 있으면 Alert 띄어주기
- [x] 다크모드에서 피커 색상 수정
- [x] 체크리스트에 맞게 앱 버전 정보, 개발자 정보, 문의 이메일 넣어주기
