### ISSUE TITLE
[REFACTOR] Trade QA 및 체크리스트 반영

### ISSUE THREAD

**Issue by juri123123** [APP-iOS4/ANBD#285]
## Description
QA와 체크리스트 
모델 수정 사항 반영

## Todo
- [x] 이미지 수정 (alert도 수정하기, 카메라 밑에 아이콘 ! )
- [x] 수정사항 없는데 버튼 활성화 되어 있는 이슈
- [x] 얼럿 레이블 삭제하기 -> 돌아가기 
- [x] 줄것, 받을 것 레이블 프레임 맞추기
