### ISSUE TITLE
[REFACTOR] 회원가입, 마이페이지 체크리스트 반영

### ISSUE THREAD

**Issue by marukim365** [APP-iOS4/ANBD#291]
## Description
회원가입, 마이페이지 체크리스트 반영

## Todo
- [x] 회원가입, 마이페이지 문자열이 길어졌을 때 뷰 확인
- [x] 폰트 크기 QA
- [ ] 마이페이지 - 설정에서 외부 라이브러리 목록 보여주기
- [x] 회원가입, 마이페이지에서 이용약관 제대로 보여주기
- [x] 회원 탈퇴 시 Auth 삭제 확인해보기

## Etc
N/A
