### ISSUE TITLE
[REFACTOR] trade & search 체크리스트 반영

### ISSUE THREAD

**Issue by juri123123** [APP-iOS4/ANBD#292]
## Description
체크리스트 반영

## TODO
- [x] 다크모드
- [x] 기본글자크기조정
- [x] 매우 긴 문자열
- [ ] 토스트 (서버 통신 문제 + etc..)
- [x] 데이터가 없는 경우 내용없음 안내 
- [x] 탭뷰 바탕색 통일
