### ISSUE TITLE
[REFACTOR] 회원가입, 마이페이지 체크리스트 반영 2

### ISSUE THREAD

**Issue by marukim365** [APP-iOS4/ANBD#300]
## Description
- 오픈소스 라이선스 확인할 수 있게 추가하기
- 탈퇴한 유저일 경우 신고하기 버튼 안보이게 하기
- 마이페이지나 설정의 빈 공간 직사각형 색상, 다크모드에서 더 잘보이게 수정하기
- 구글 로그인 버튼 제거하기
- UserDefaults에서 UseInfo 제거하기

## Todo
- [x] 오픈소스 라이선스 확인할 수 있게 추가하기
- [x] 탈퇴한 유저일 경우 신고하기 버튼 안보이게 하기
- [x] 마이페이지나 설정의 빈 공간 직사각형 색상, 다크모드에서 더 잘보이게 수정하기
- [x] 구글 로그인 버튼 제거하기
- [x] UserDefaults에서 UseInfo 제거하기

## Etc
 N/A
