### ISSUE TITLE
[REFACTOR] QA 반영

### ISSUE THREAD

**Issue by marukim365** [APP-iOS4/ANBD#336]
## Description
2024년 5월 8일 QA 내용 반영

## Todo
- [x] 설정에 [캐시 데이터 삭제하기] 메뉴 추가
- [x] 글을 통해 로그인한 유저의 프로필 정보에 들어갔을 때 네비게이션 이슈 해결
- [x] 유저의 작성 글이 없을 때, 작성하러 가기 버튼 추가하기

## Etc
추가적인 작업 내용이 생길 시 Todo에 추가하겠습니다.
