### ISSUE TITLE
[REFACTOR] Toast & QA

### ISSUE THREAD

**Issue by juri123123** [APP-iOS4/ANBD#337]
## Todo
- [x] Toast 메세지 수정
- [x] custom alert title -> 거래글 삭제
- [x] 거래 방식만 변경했을 때 수정 완료 버튼 활성화
- [x] 사진 등록 윗 부분 패딩 줄이기
- [x] 홈 탭 바꿔쓰기에 거래완료 품목 제거
- [x] 홈 -> 더보기 카테고리 필터가 나눔거래 탭에도 적용됨
