### ISSUE TITLE
[Design] Alert 및 Error 문구 수정

### ISSUE THREAD

**Issue by marukim365** [APP-iOS4/ANBD#346]
## Description
Alert과 Error Toast 문구를 통일감 있게 수정하고자 함.

## Todo
- [x] Trade Delete Alert 문구 수정
- [x] 메뉴의 신고하기 문구 수정
- [x] Error Toast 문구 수정

## Etc
N/A
