### ISSUE TITLE
[FEATURE] HomeView - ANBD 페이지 연결

### ISSUE THREAD

**Issue by choijungp** [APP-iOS4/ANBD#66]
## Description
HomeView에서 아껴쓰기, 나눠쓰기, 다시쓰기, 바꿔쓰기 Cell 혹은 더보기를 눌렀을 때 페이지 이동 연결

## Todo
- [x] ArticleCell to ArticleDetailView
- [x] TradeCell to TradeDetailView
- [x] 아껴쓰기, 다시쓰기 to ArticleView 
- [x] 나눠쓰기, 바꿔쓰기 to TradeView
