### ISSUE TITLE
[REFACTOR] HomeView 피드백 및 QA 반영

### ISSUE THREAD

**Issue by choijungp** [APP-iOS4/ANBD#89]
## Description
HomeView 유민영 강사님 피드백 및 마루 QA 반영

## Todo
- [x] 광고 배너 케로셀뷰 -> 탭뷰 수정
- [x] 아껴쓰기, 나눠쓰기, 바꿔쓰기, 다시쓰기 섹션 Title -> weight Bold로 수정
- [x] 아껴쓰기, 나눠쓰기, 바꿔쓰기, 다시쓰기 섹션 사이 사이 vertical 간격이 넓음
