### ISSUE TITLE
[REFACTOR] UI 피드백 반영

### ISSUE THREAD

**Issue by juri123123** [APP-iOS4/ANBD#90]
## Description
유민영 강사님 피드백 반영

## Todo

- [x]  text title bold
- [x]  categorydDividerList -> onTapGesture 깜빡거리는거 해결
- [x] 마지막 cell과 글쓰기 버튼 간격
