### ISSUE TITLE
[REFACTOR] QA 반영

### ISSUE THREAD

**Issue by juri123123** [APP-iOS4/ANBD#99]
## Description
마루의 QA 반영

## Todo
- [x] confirmation dialog로 변경
- [x] custom alert
- [x] 디테일 뷰 symbol 크기 키우기
- [x] 사진 터치했을 때 사진 커지게
- [x] createView clear 작동
- [x] createView 작성 중 취소 버튼 클릭시 alert
